CREATE DATABASE empresa;

USE empresa;

CREATE TABLE persona (
 `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 `nombres` VARCHAR(45) DEFAULT NULL,
 `apellidos` VARCHAR(45) DEFAULT NULL,
 `edad` INT(10) UNSIGNED DEFAULT NULL, PRIMARY KEY (`id`)
);